import NONE from "./assets/NONE.png";
import WALL from "./assets/WALL.png";
import START_FLOOR from "./assets/START_FLOOR.png";
import OTHER from "./assets/OTHER.png";
import APPLE from "./assets/APPLE.png";
import STONE from "./assets/STONE.png";
import FLYING_PILL from "./assets/FLYING_PILL.png";
import FURY_PILL from "./assets/FURY_PILL.png";
import GOLD from "./assets/GOLD.png";
import HEAD_DOWN from "./assets/HEAD_DOWN.png";
import HEAD_LEFT from "./assets/HEAD_LEFT.png";
import HEAD_RIGHT from "./assets/HEAD_RIGHT.png";
import HEAD_UP from "./assets/HEAD_UP.png";
import HEAD_DEAD from "./assets/HEAD_DEAD.png";
import HEAD_EVIL from "./assets/HEAD_EVIL.png";
import HEAD_FLY from "./assets/HEAD_FLY.png";
import HEAD_SLEEP from "./assets/HEAD_SLEEP.png";
import TAIL_END_DOWN from "./assets/TAIL_END_DOWN.png";
import TAIL_END_LEFT from "./assets/TAIL_END_LEFT.png";
import TAIL_END_UP from "./assets/TAIL_END_UP.png";
import TAIL_END_RIGHT from "./assets/TAIL_END_RIGHT.png";
import TAIL_INACTIVE from "./assets/TAIL_INACTIVE.png";
import BODY_HORIZONTAL from "./assets/BODY_HORIZONTAL.png";
import BODY_VERTICAL from "./assets/BODY_VERTICAL.png";
import BODY_LEFT_DOWN from "./assets/BODY_LEFT_DOWN.png";
import BODY_LEFT_UP from "./assets/BODY_LEFT_UP.png";
import BODY_RIGHT_DOWN from "./assets/BODY_RIGHT_DOWN.png";
import BODY_RIGHT_UP from "./assets/BODY_RIGHT_UP.png";
import ENEMY_HEAD_DOWN from "./assets/ENEMY_HEAD_DOWN.png";
import ENEMY_HEAD_LEFT from "./assets/ENEMY_HEAD_LEFT.png";
import ENEMY_HEAD_RIGHT from "./assets/ENEMY_HEAD_RIGHT.png";
import ENEMY_HEAD_UP from "./assets/ENEMY_HEAD_UP.png";
import ENEMY_HEAD_DEAD from "./assets/ENEMY_HEAD_DEAD.png";
import ENEMY_HEAD_EVIL from "./assets/ENEMY_HEAD_EVIL.png";
import ENEMY_HEAD_FLY from "./assets/ENEMY_HEAD_FLY.png";
import ENEMY_HEAD_SLEEP from "./assets/ENEMY_HEAD_SLEEP.png";
import ENEMY_TAIL_END_DOWN from "./assets/ENEMY_TAIL_END_DOWN.png";
import ENEMY_TAIL_END_LEFT from "./assets/ENEMY_TAIL_END_LEFT.png";
import ENEMY_TAIL_END_UP from "./assets/ENEMY_TAIL_END_UP.png";
import ENEMY_TAIL_END_RIGHT from "./assets/ENEMY_TAIL_END_RIGHT.png";
import ENEMY_TAIL_INACTIVE from "./assets/ENEMY_TAIL_INACTIVE.png";
import ENEMY_BODY_HORIZONTAL from "./assets/ENEMY_BODY_HORIZONTAL.png";
import ENEMY_BODY_VERTICAL from "./assets/ENEMY_BODY_VERTICAL.png";
import ENEMY_BODY_LEFT_DOWN from "./assets/ENEMY_BODY_LEFT_DOWN.png";
import ENEMY_BODY_LEFT_UP from "./assets/ENEMY_BODY_LEFT_UP.png";
import ENEMY_BODY_RIGHT_DOWN from "./assets/ENEMY_BODY_RIGHT_DOWN.png";
import ENEMY_BODY_RIGHT_UP from "./assets/ENEMY_BODY_RIGHT_UP.png";

export enum ELEMENT_TYPE {
  NONE = ' ',
  WALL = '☼',
  START_FLOOR = '#',
  OTHER = '?',
  APPLE = '○',
  STONE = '●',
  FLYING_PILL = '©',
  FURY_PILL = '®',
  GOLD = '$',
  HEAD_DOWN = '▼',
  HEAD_LEFT = '◄',
  HEAD_RIGHT = '►',
  HEAD_UP = '▲',
  HEAD_DEAD = '☻',
  HEAD_EVIL = '♥',
  HEAD_FLY = '♠',
  HEAD_SLEEP = '&',
  TAIL_END_DOWN = '╙',
  TAIL_END_LEFT = '╘',
  TAIL_END_UP = '╓',
  TAIL_END_RIGHT = '╕',
  TAIL_INACTIVE = '~',
  BODY_HORIZONTAL = '═',
  BODY_VERTICAL = '║',
  BODY_LEFT_DOWN = '╗',
  BODY_LEFT_UP = '╝',
  BODY_RIGHT_DOWN = '╔',
  BODY_RIGHT_UP = '╚',
  ENEMY_HEAD_DOWN = '˅',
  ENEMY_HEAD_LEFT = '<',
  ENEMY_HEAD_RIGHT = '>',
  ENEMY_HEAD_UP = '˄',
  ENEMY_HEAD_DEAD = '☺',
  ENEMY_HEAD_EVIL = '♣',
  ENEMY_HEAD_FLY = '♦',
  ENEMY_HEAD_SLEEP = 'ø',
  ENEMY_TAIL_END_DOWN = '¤',
  ENEMY_TAIL_END_LEFT = '×',
  ENEMY_TAIL_END_UP = 'æ',
  ENEMY_TAIL_END_RIGHT = 'ö',
  ENEMY_TAIL_INACTIVE = '*',
  ENEMY_BODY_HORIZONTAL = '─',
  ENEMY_BODY_VERTICAL = '│',
  ENEMY_BODY_LEFT_DOWN = '┐',
  ENEMY_BODY_LEFT_UP = '┘',
  ENEMY_BODY_RIGHT_DOWN = '┌',
  ENEMY_BODY_RIGHT_UP = '└',
}

export const IMAGES_MAP = {
  [ELEMENT_TYPE.NONE]: NONE,
  [ELEMENT_TYPE.WALL]: WALL,
  [ELEMENT_TYPE.START_FLOOR]: START_FLOOR,
  [ELEMENT_TYPE.OTHER]: OTHER,
  [ELEMENT_TYPE.APPLE]: APPLE,
  [ELEMENT_TYPE.STONE]: STONE,
  [ELEMENT_TYPE.FLYING_PILL]: FLYING_PILL,
  [ELEMENT_TYPE.FURY_PILL]: FURY_PILL,
  [ELEMENT_TYPE.GOLD]: GOLD,
  [ELEMENT_TYPE.HEAD_DOWN]: HEAD_DOWN,
  [ELEMENT_TYPE.HEAD_LEFT]: HEAD_LEFT,
  [ELEMENT_TYPE.HEAD_RIGHT]: HEAD_RIGHT,
  [ELEMENT_TYPE.HEAD_UP]: HEAD_UP,
  [ELEMENT_TYPE.HEAD_DEAD]: HEAD_DEAD,
  [ELEMENT_TYPE.HEAD_EVIL]: HEAD_EVIL,
  [ELEMENT_TYPE.HEAD_FLY]: HEAD_FLY,
  [ELEMENT_TYPE.HEAD_SLEEP]: HEAD_SLEEP,
  [ELEMENT_TYPE.TAIL_END_DOWN]: TAIL_END_DOWN,
  [ELEMENT_TYPE.TAIL_END_LEFT]: TAIL_END_LEFT,
  [ELEMENT_TYPE.TAIL_END_UP]: TAIL_END_UP,
  [ELEMENT_TYPE.TAIL_END_RIGHT]: TAIL_END_RIGHT,
  [ELEMENT_TYPE.TAIL_INACTIVE]: TAIL_INACTIVE,
  [ELEMENT_TYPE.BODY_HORIZONTAL]: BODY_HORIZONTAL,
  [ELEMENT_TYPE.BODY_VERTICAL]: BODY_VERTICAL,
  [ELEMENT_TYPE.BODY_LEFT_DOWN]: BODY_LEFT_DOWN,
  [ELEMENT_TYPE.BODY_LEFT_UP]: BODY_LEFT_UP,
  [ELEMENT_TYPE.BODY_RIGHT_DOWN]: BODY_RIGHT_DOWN,
  [ELEMENT_TYPE.BODY_RIGHT_UP]: BODY_RIGHT_UP,
  [ELEMENT_TYPE.ENEMY_HEAD_DOWN]: ENEMY_HEAD_DOWN,
  [ELEMENT_TYPE.ENEMY_HEAD_LEFT]: ENEMY_HEAD_LEFT ,
  [ELEMENT_TYPE.ENEMY_HEAD_RIGHT]: ENEMY_HEAD_RIGHT,
  [ELEMENT_TYPE.ENEMY_HEAD_UP]: ENEMY_HEAD_UP,
  [ELEMENT_TYPE.ENEMY_HEAD_DEAD]: ENEMY_HEAD_DEAD,
  [ELEMENT_TYPE.ENEMY_HEAD_EVIL]: ENEMY_HEAD_EVIL,
  [ELEMENT_TYPE.ENEMY_HEAD_FLY]: ENEMY_HEAD_FLY,
  [ELEMENT_TYPE.ENEMY_HEAD_SLEEP]: ENEMY_HEAD_SLEEP,
  [ELEMENT_TYPE.ENEMY_TAIL_END_DOWN]: ENEMY_TAIL_END_DOWN,
  [ELEMENT_TYPE.ENEMY_TAIL_END_LEFT]: ENEMY_TAIL_END_LEFT,
  [ELEMENT_TYPE.ENEMY_TAIL_END_UP]: ENEMY_TAIL_END_UP,
  [ELEMENT_TYPE.ENEMY_TAIL_END_RIGHT]: ENEMY_TAIL_END_RIGHT,
  [ELEMENT_TYPE.ENEMY_TAIL_INACTIVE]: ENEMY_TAIL_INACTIVE,
  [ELEMENT_TYPE.ENEMY_BODY_HORIZONTAL]: ENEMY_BODY_HORIZONTAL,
  [ELEMENT_TYPE.ENEMY_BODY_VERTICAL]: ENEMY_BODY_VERTICAL,
  [ELEMENT_TYPE.ENEMY_BODY_LEFT_DOWN]: ENEMY_BODY_LEFT_DOWN,
  [ELEMENT_TYPE.ENEMY_BODY_LEFT_UP]: ENEMY_BODY_LEFT_UP,
  [ELEMENT_TYPE.ENEMY_BODY_RIGHT_DOWN]: ENEMY_BODY_RIGHT_DOWN,
  [ELEMENT_TYPE.ENEMY_BODY_RIGHT_UP]: ENEMY_BODY_RIGHT_UP,
};